{{- if .Values.keda.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "simple-web.fullname" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "simple-web.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    name: {{ include "simple-web.fullname" . }}
  minReplicaCount: {{ .Values.keda.minReplicaCount }}
  maxReplicaCount: {{ .Values.keda.maxReplicaCount }}
  pollingInterval: {{ .Values.keda.scaledObject.pollingInterval }}
  cooldownPeriod: {{ .Values.keda.scaledObject.cooldownPeriod }}
  advanced:
    restoreToOriginalReplicaCount: {{ .Values.keda.scaledObject.advanced.restoreToOriginalReplicaCount }}
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: {{ .Values.keda.scaledObject.advanced.horizontalPodAutoscalerConfig.behavior.scaleDown.stabilizationWindowSeconds }}
        scaleUp:
          stabilizationWindowSeconds: {{ .Values.keda.scaledObject.advanced.horizontalPodAutoscalerConfig.behavior.scaleUp.stabilizationWindowSeconds }}
  triggers:
    {{- toYaml .Values.keda.triggers | nindent 4 }}
{{- end }}

